// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHa7iUhrC7-L4Vd1VgtdBfSfeSPOo1uU4',
    appId: '1:775869697987:web:c0417d31985dacded13776',
    messagingSenderId: '775869697987',
    projectId: 'fir-project2-fb36d',
    authDomain: 'fir-project2-fb36d.firebaseapp.com',
    databaseURL: 'https://fir-project2-fb36d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project2-fb36d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7hpJKEz1nlGZ6B0BodEBO1t_aGI6LviE',
    appId: '1:775869697987:android:64a732b98d1a529cd13776',
    messagingSenderId: '775869697987',
    projectId: 'fir-project2-fb36d',
    databaseURL: 'https://fir-project2-fb36d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project2-fb36d.appspot.com',
  );
}
